# Generated by Django 5.1.2 on 2026-01-11 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=60)),
                ('entity_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=60)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('parent_name', models.CharField(blank=True, default='', max_length=120)),
                ('parent_phone', models.CharField(blank=True, default='', max_length=50)),
                ('parent_email', models.EmailField(blank=True, default='', max_length=254)),
                ('preferred_language', models.CharField(blank=True, default='', max_length=50)),
                ('insurance', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referring_provider', models.CharField(blank=True, default='', max_length=120)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('FLAGGED', 'Flagged by Provider'), ('INTAKE_CREATED', 'Intake Created'), ('REVIEW_PENDING', 'Review Pending'), ('REVIEW_COMPLETED', 'Review Completed'), ('PLAN_READY', 'Plan Ready'), ('PARENT_CONTACTED', 'Parent Contacted'), ('PARENT_CONFIRMED', 'Parent Confirmed'), ('SLOT_ASSIGNED', 'Slot Assigned'), ('SCHEDULED_INTERNAL', 'Scheduled (Internal)'), ('ACTIVE_THERAPY', 'Active Therapy'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped / Not Candidate')], default='FLAGGED', max_length=40)),
                ('priority', models.CharField(blank=True, default='Normal', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vt_referrals_owned', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='CALL', max_length=30)),
                ('outcome', models.CharField(blank=True, default='', max_length=60)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.referral')),
            ],
        ),
    ]
